const properties = [
  {
    id: 1,
    banner_image: 'https://calvin.edu/sites/default/files/styles/wide/public/place/BV.jpg',
    address: '3275 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 3,
    baths: 0.5,
    contact_phone: '(616) 111-1111',
    contact_email: 'propertyID1@calvin.edu',
    rating: 4.5,
    estimated_cost: 500,
    distance_from_campus: 0.0,
    pet_friendly: false,

  },
  {
    id: 2,
    banner_image: '',
    address: '3260 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 4,
    baths: 2,
    contact_phone: '(616) 222-2222',
    contact_email: 'propertyID2@calvin.edu',
    rating: 3.8,
    estimated_cost: 750,
    distance_from_campus: 0.5,
    pet_friendly: true,
  },
  {
    id: 3,
    banner_image: '',
    address: '3250 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 2,
    baths: 1,
    contact_phone: '(616) 333-3333',
    contact_email: 'propertyID3@calvin.edu',
    rating: 4.2,
    estimated_cost: 600,
    distance_from_campus: 0.3,
    pet_friendly: false,
  },
  {
    id: 4,
    banner_image: '',
    address: '3240 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 3,
    baths: 1.5,
    contact_phone: '(616) 444-4444',
    contact_email: 'propertyID4@calvin.edu',
    rating: 4.0,
    estimated_cost: 700,
    distance_from_campus: 0.4,
    pet_friendly: true,
  },
  {
    id: 5,
    banner_image: '',
    address: '3230 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 5,
    baths: 2.5,
    contact_phone: '(616) 555-5555',
    contact_email: 'propertyID5@calvin.edu',
    rating: 4.7,
    estimated_cost: 900,
    distance_from_campus: 0.6,
    pet_friendly: true,
  },
  {
    id: 6,
    banner_image: '',
    address: '3220 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 1,
    baths: 1,
    contact_phone: '(616) 666-6666',
    contact_email: 'propertyID6@calvin.edu',
    rating: 3.5,
    estimated_cost: 450,
    distance_from_campus: 0.2,
    pet_friendly: false,
  },
  {
    id: 7,
    banner_image: 'https://calvin.edu/sites/default/files/styles/wide/public/place/KHvR_1.jpg',
    address: '3245 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 3,
    baths: 2,
    contact_phone: '',
    contact_email: 'propertyID7@calvin.edu',
    rating: 4.3,
    estimated_cost: 800,
    distance_from_campus: 0.7,
    pet_friendly: true,
  },
  {
    id: 8,
    banner_image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/61/84/5c/main-entrance.jpg',
    address: '1800 E Beltline Ave SE, Grand Rapids, MI 49546',
    beds: 2,
    baths: 1,
    contact_phone: '',
    contact_email: '',
    rating: 4.1,
    estimated_cost: 650,
    distance_from_campus: 0.3,
    pet_friendly: false,
  },
];

export default properties;