const properties = [
  {
    id: 1,
    banner_image: 'https://calvin.edu/sites/default/files/styles/wide/public/place/BV.jpg',
    address: '3275 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 3,
    baths: 0.5,
    contact_phone: '(616) 111-1111',
    contact_email: 'propertyID1@calvin.edu',
  },
  {
    id: 2,
    banner_image: '',
    address: '3260 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 4,
    baths: 2,
    contact_phone: '(616) 222-2222',
    contact_email: 'propertyID2@calvin.edu',
  },
  {
    id: 3,
    banner_image: '',
    address: '3200 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 2,
    baths: 1,
    contact_phone: '(616) 333-3333',
    contact_email: 'propertyID3@calvin.edu',
  },
  {
    id: 4,
    banner_image: '',
    address: '3220 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 3,
    baths: 1.5,
    contact_phone: '(616) 444-4444',
    contact_email: '',
  },
  {
    id: 5,
    banner_image: '',
    address: '3235 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 5,
    baths: 3,
    contact_phone: '(616) 555-5555',
    contact_email: '',
  },
  {
    id: 6,
    banner_image: '',
    address: '3255 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 4,
    baths: 2.5,
    contact_phone: '',
    contact_email: 'propertyID6@calvin.edu',
  },
  {
    id: 7,
    banner_image: 'https://calvin.edu/sites/default/files/styles/wide/public/place/KHvR_1.jpg',
    address: '3245 Knight Way Southeast, Grand Rapids, MI 49546',
    beds: 3,
    baths: 2,
    contact_phone: '',
    contact_email: 'propertyID7@calvin.edu',
  },
  {
    id: 8,
    banner_image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/61/84/5c/main-entrance.jpg',
    address: '1800 E Beltline Ave SE, Grand Rapids, MI 49546',
    beds: 2,
    baths: 1,
    contact_phone: '',
    contact_email: '',
  },
];

export default properties;