// rating, contact_phone, contact_email, and pet_friendly are NOT correct and are arbitratily set for demonstration purposes

const properties = [
  {
    id: 1,
    banner_image: null,
    address: '1610 Rossman Ave SE, Grand Rapids, MI 49507',
    beds: 5,
    baths: 2.5,
    landlord_name: 'Erik Kraayeveld',
    contact_phone: '616-111-2222',
    contact_email: 'ekraayeveld@gmail.com',
    estimated_cost: 2200,
    distance_from_campus: 2.2,
    distance_from_bus_stop: 0.5,
    pet_friendly: true,
    rating: 4.5,
  },
  {
    id: 2,
    banner_image: null,
    address: '1024 Burton St SE, Grand Rapids, MI 49507',
    beds: 4,
    baths: 2,
    landlord_name: 'Erik Kraayeveld',
    contact_phone: '616-111-2222',
    contact_email: 'ekraayeveld@gmail.com',
    estimated_cost: 1750,
    distance_from_campus: 2.8,
    distance_from_bus_stop: 0.3,
    pet_friendly: false,
    rating: 4.0,
  },
  {
    id: 3,
    banner_image: null,
    address: '1421 Sherman St SE, Grand Rapids, MI 49506',
    beds: 5,
    baths: 2,
    landlord_name: 'Erik Kraayeveld',
    contact_phone: '616-111-2222',
    contact_email: 'ekraayeveld@gmail.com',
    estimated_cost: 2000,
    distance_from_campus: 2.8,
    distance_from_bus_stop: 0.4,
    pet_friendly: false,
    rating: 4.0,
  },
  {
    id: 4,
    banner_image: null,
    address: '249 Alger St SE, Grand Rapids, MI 49507',
    beds: 5,
    baths: 2,
    landlord_name: 'Erik Kraayeveld',
    contact_phone: '616-111-2222',
    contact_email: 'ekraayeveld@gmail.com',
    estimated_cost: 1950,
    distance_from_campus: 3.8,
    distance_from_bus_stop: 0.3,
    pet_friendly: false,
    rating: 2.4,
  },
  {
    id: 5,
    banner_image: null,
    address: '1314 Boston St SE, Grand Rapids, MI 40507',
    beds: 4,
    baths: 2,
    landlord_name: 'Erik Kraayeveld',
    contact_phone: '616-111-2222',
    contact_email: 'ekraayeveld@gmail.com',
    estimated_cost: 1700,
    distance_from_campus: 2.5,
    distance_from_bus_stop: 0.2,
    pet_friendly: true,
    rating: 3.5,
  },
  {
    id: 6,
    banner_image: null,
    address: '118 National Ave SW, Grand Rapids, MI 49504',
    beds: 2,
    baths: 1,
    landlord_name: 'Cathy Sevigny',
    contact_phone: null,
    contact_email: null,
    estimated_cost: 1475,
    distance_from_campus: 5.4,
    distance_from_bus_stop: 0.2,
    pet_friendly: true,
    rating: 3.0,
  },
  {
    id: 7,
    banner_image: null,
    address: '2010 Deciduous Dr, Grand Rapids MI 49505',
    beds: 2,
    baths: 3,
    landlord_name: 'Continental Properties Co',
    contact_phone: '616-123-4567',
    contact_email: 'contact@continentalProperties.org',
    estimated_cost: 2280,
    distance_from_campus: 4.8,
    distance_from_bus_stop: 0.7,
    pet_friendly: false,
    rating: 4.9,
  },
  {
    id: 8,
    banner_image: null,
    address: '2142 Stafford Ave SW, Grand Rapids, MI 49507',
    beds: 3,
    baths: 1,
    landlord_name: 'Brian Tagg',
    contact_phone: '616-987-6543',
    contact_email: 'btagg@yahoo.com',
    estimated_cost: 2000,
    distance_from_campus: 4.5,
    distance_from_bus_stop: 0.3,
    pet_friendly: true,
    rating: 3.4,
  },
  {
    id: 9,
    banner_image: null,
    address: '3476 Bluebird Ave SW, Wyoming MI, 49519',
    beds: 3,
    baths: 1,
    landlord_name: 'Brian Tagg',
    contact_phone: '616-987-6543',
    contact_email: 'btagg@yahoo.com',
    estimated_cost: 2100,
    distance_from_campus: 7.4,
    distance_from_bus_stop: 0.3,
    pet_friendly: false,
    rating: 4.8,
  },
  {
    id: 10,
    banner_image: null,
    address: '1126 Merrifield St SE, Grand Rapids, MI 49507',
    beds: 4,
    baths: 1,
    landlord_name: 'Shift Management LLC',
    contact_phone: null,
    contact_email: null,
    estimated_cost: 1895,
    distance_from_campus: 2.7,
    distance_from_bus_stop: 0.2,
    pet_friendly: false,
    rating: 4.7,
  },
  {
    id: 11,
    banner_image: null,
    address: '636 Innes St NE, Grand Rapids, MI 49503',
    beds: 2,
    baths: 1,
    landlord_name: 'Aiesha Reynolds',
    contact_phone: '616-555-5555',
    contact_email: 'AieshaReynolds@outlook.com',
    estimated_cost: 1000,
    distance_from_campus: 4.2,
    distance_from_bus_stop: 0.4,
    pet_friendly: true,
    rating: 3.9,
  },
  {
    id: 12,
    banner_image: null,
    address: '471 Emerald Ave NE, Grand Rapids, MI 49503',
    beds: 4,
    baths: 1,
    landlord_name: 'HCW Realty',
    contact_phone: null,
    contact_email: null,
    estimated_cost: 1900,
    distance_from_campus: 4.2,
    distance_from_bus_stop: 0.2,
    pet_friendly: false,
    rating: 4.2,
  },
  {
    id: 13,
    banner_image: null,
    address: '1020 Sigsbee St SE, Grand Rapids, MI 49506',
    beds: 5,
    baths: 2,
    landlord_name: 'Rental Properties Consultant LLC',
    contact_phone: null,
    contact_email: null,
    estimated_cost: 3200,
    distance_from_campus: 3.3,
    distance_from_bus_stop: 0.1,
    pet_friendly: true,
    rating: 4.6,
  },
  
].sort((a, b) => a.rating < b.rating ? 1 : -1);

export default properties;